"""empty message

Revision ID: a5c4e873e46f
Revises: 
Create Date: 2018-12-10 16:54:50.338832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5c4e873e46f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('user_pic', sa.String(), nullable=True),
    sa.Column('post_name', sa.String(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('boss_id', sa.Integer(), nullable=True),
    sa.Column('hierarchy', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['boss_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_hierarchy'), 'users', ['hierarchy'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_hierarchy'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
